Fix error for the packagegroup-agl-ic-core
After the kirkstone, packagegroup-agl-ic-core out the error message
in build time.

Ex:
ERROR: mc:agl-container-cluster:packagegroup-agl-ic-core-1.0-r0
  do_package_write_rpm: An allarch packagegroup shouldn't depend on
  packages which are dynamically renamed (libclusterapi-dbg to
  libcluster-api-dbg)

This error is depend on this commit.
   https://www.mail-archive.com/openembedded-core@lists.openembedded.org/msg155223.html

This patch add "PACKAGE_ARCH = "${TUNE_PKGARCH}"" to package group recipe
to fix this issue.

Bug-AGL: SPEC-4552

Signed-off-by: Naoto Yamaguchi <naoto.yamaguchi@aisin.co.jp>
Change-Id: I70f56e4a96a658cbcefa48ac688b49382b299879
(cherry picked from commit 73676a6fd1ccede1f804375640b93ddd6b92118e)